#ifndef CANDY_NETSTACK_LWIPOPTS_H
#define CANDY_NETSTACK_LWIPOPTS_H

#define NO_SYS 1
#define LWIP_NETCONN 0
#define LWIP_SOCKET 0
#define SYS_LIGHTWEIGHT_PROT 0

#define LWIP_TIMERS 1

#define IP_FORWARD 0

#define LWIP_TCP 1
#define LWIP_UDP 0
#define LWIP_RAW 0
#define LWIP_ICMP 1
#define LWIP_DNS 0
#define LWIP_DHCP 0
#define LWIP_AUTOIP 0
#define LWIP_IGMP 0
#define LWIP_ARP 0
#define LWIP_ETHERNET 0
#define LWIP_NETIF_API 0
#define LWIP_NETIF_LOOPBACK 0
#define LWIP_HAVE_LOOPIF 0

#define LWIP_IPV4 1
#define LWIP_IPV6 0

#define MEM_ALIGNMENT 4U
#define MEM_LIBC_MALLOC 1
#define MEMP_MEM_MALLOC 1

#define MEMP_NUM_TCP_PCB 4096
#define MEMP_NUM_TCP_PCB_LISTEN 16
#define MEMP_NUM_TCP_SEG 4096
#define MEMP_NUM_PBUF 4096
#define MEMP_NUM_REASSDATA 1
#define PBUF_POOL_SIZE 0

#define TCP_MSS 1460
#define TCP_WND (32 * TCP_MSS)
#define TCP_SND_BUF (32 * TCP_MSS)
#define TCP_SND_QUEUELEN ((4 * TCP_SND_BUF) / TCP_MSS)
#define TCP_QUEUE_OOSEQ 1

#define LWIP_NETIF_STATUS_CALLBACK 0
#define LWIP_NETIF_LINK_CALLBACK 0
#define LWIP_NETIF_HOSTNAME 0

#define CHECKSUM_GEN_IP 1
#define CHECKSUM_GEN_TCP 1
#define CHECKSUM_CHECK_IP 1
#define CHECKSUM_CHECK_TCP 1

#define LWIP_STATS 0
#define LWIP_STATS_DISPLAY 0

#define LWIP_DEBUG 0

#endif
